[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.dc.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
